server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost8761/eureka
  

spring:
  cloud:
    gateway:
      routes:
        #Route Mapping
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication/**
          filters:
            - RewritePath=/authentication(?<segment>/?.*), $\{segment}

            #Route Mapping
        - id: bookings-management
          uri: lb://bookings-management
          predicates:
            - Path=/booking-Management/**
          filters:
            - RewritePath=/booking-Management(?<segment>/?.*), $\{segment}

        #Route Mapping
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
          filters:
            - RewritePath=/chat(?<segment>/?.*), $\{segment}

        #Route Mapping
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/email/**
          filters:
            - RewritePath=/email(?<segment>/?.*), $\{segment}


        #Route Mapping
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment(?<segment>/?.*), $\{segment}

        #Route Mapping
        - id: team-up
          uri: lb://team-up
          predicates:
            - Path=/team/**
          filters:
            - RewritePath=/team(?<segment>/?.*), $\{segment}

        #Route Mapping
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>/?.*), $\{segment}

        #Route Mapping
        - id: config-server
          uri: lb://config-server
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config(?<segment>/?.*), $\{segment}


        #Route Mapping
        - id: product-webapp
          uri: lb://product-webapp
          predicates:
            - Path=/**
          filters:
            - RewritePath=(?<segment>/?.*), $\{segment}






