server:
  port: 8095
spring:
  datasource:
    name: user
    url: jdbc:mysql://localhost:3306/user?useSSL=false
    username: root
    password: Happy@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  cloud:
    config:
      import-check:
        enabled: false
management:
  security:
    enabled: false
  application:
    name: authentication-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

 
