server:
  port: 8085

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Email


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost8761/eureka


service:
  emailId: sportsarenaemailservice@gmail.com
  password: hrcrvkrrowwusfcz
