server:
  port: 8085

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Email
  mail:
    smtp:
      host: smtp.gmail.com
      port: 465
      ssl:
        enable: true
      auth: true
    id: sportsarenaemailservice@gmail.com
    password: hrcrvkrrowwusfcz



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost8761/eureka
