server:
  port: 8085

spring:
  mail:
    id: sportsarenaemailservice@gmail.com
    password: hrcrvkrrowwusfcz
    


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost8761/eureka
