server:
  port: 8082
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: TeamupDB


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost8761/eureka  
