--- 
eureka: 
  client: 
    fetch-registry: true
    register-with-eureka: true
  service-url: 
    defaultZone: "http://localhost8761/eureka"
server: 
  port: 8081
spring: 
  data: 
    mongodb: 
      database: players
      host: localhost
      port: 27017
      auto-index-creation: true
  datasource: 
    driver-name: mongodb.jdbc.MongoDriver
  
